### ISSUE TITLE
BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by victorlearned** [jescalan/autoprefixer-stylus#179]
This is failing because autoprefixer-stylus is targeting a version of autoprefixer(7.1) that relies on an old version of browserslist. Can we update it to a later verson that uses browserslist 3+?

+-- autoprefixer-stylus@0.14.0
| +-- autoprefixer@7.1.0
| | +-- browserslist@2.11.3

PS C:\repos\react-catch-of-the-day\catch-of-the-day> npm run styles:watch

> cotd@0.0.3 styles:watch C:\repos\react-catch-of-the-day\catch-of-the-day
> stylus -u autoprefixer-stylus -w ./src/css/style.styl -o ./src/css/style.css

C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\postcss\lib\lazy-result.js:273
            throw error;
            ^
BrowserslistError: Unknown browser query `dead`
    at C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\browserslist\index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\browserslist\index.js:132:18)
    at browserslist (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\browserslist\index.js:224:16)
    at Browsers.parse (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\autoprefixer\lib\browsers.js:52:30)
    at loadPrefixes (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\autoprefixer\lib\autoprefixer.js:67:24)
    at plugin (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\autoprefixer\lib\autoprefixer.js:78:24)
    at LazyResult.run (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\postcss\lib\lazy-result.js:270:20)
    at LazyResult.sync (C:\repos\react-catch-of-the-day\catch-of-the-day\node_modules\postcss\lib\lazy-result.js:257:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cotd@0.0.3 styles:watch: `stylus -u autoprefixer-stylus -w ./src/css/style.styl -o ./src/css/style.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cotd@0.0.3 styles:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by RonanC** [comment]
I'm getting the same issue here.

**Comment by bisonbleu** [comment]
I get the same error.

I'm stuck at the beginning of video #22 **Animating React** because running the prescribed command `npm run watch` leads to the error mentioned by @victorlearned.

**Comment by jescalan** [comment]
I don't know anything about animating react videos, but I do know that if you want to update dependencies on an open source project, the best way is to contribute! Anyone want to take a stab at a PR?

**Comment by bisonbleu** [comment]
@jescalan Apologies, I was issue hopping searching for a fix and though the present issue was directly linked to the [previous one](https://github.com/wesbos/React-For-Beginners-Starter-Files/pull/99), but after a closer look, it is only indirectly connected.

p.s. Could not agree more about contributing back. I've been active in Open Source for more than 10 years and where I can I do. In the present case, the best I can do with the knowledge I got is report. Cheers!

**Comment by brwnrclse** [comment]
Hello @jescalan I've got a PR here that should fix the issue -> https://github.com/jescalan/autoprefixer-stylus/pull/180
